name: TWS Update

on:
  push:
    paths:
      - 'pkgs/ib-tws/**'
  repository_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          cd "$GITHUB_WORKSPACE/pkgs/ib-tws" && ./update.sh